!
! leaf4 (AS 65014)
!  eth1 -> spine1   10.4.1.0/31
!  eth2 -> spine2   10.4.2.0/31
!  eth9 -> host4   10.14.0.1/24 (host network 10.14.0.0/24)
!
frr defaults datacenter
hostname leaf4
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.14/32
!
interface eth1
 ip address 10.4.1.0/31
!
interface eth2
 ip address 10.4.2.0/31
!
interface eth9
 ip address 10.14.0.1/24
!
router bgp 65014
 bgp router-id 10.0.0.14
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 no bgp default ipv4-unicast
 timers bgp 3 9
 !
 neighbor SPINE peer-group
 neighbor SPINE advertisement-interval 0
 neighbor SPINE timers connect 5
 !
 neighbor 10.4.1.1 remote-as 65000
 neighbor 10.4.1.1 peer-group SPINE
 neighbor 10.4.2.1 remote-as 65001
 neighbor 10.4.2.1 peer-group SPINE
 !
 address-family ipv4 unicast
  network 10.0.0.14/32
  network 10.14.0.0/24
  neighbor SPINE activate
  neighbor SPINE route-map ALLOW-ALL in
  neighbor SPINE route-map LOCAL-ONLY out
  maximum-paths 64
 exit-address-family
!
ip prefix-list LOCAL-PREFIXES seq 10 permit 10.0.0.14/32
ip prefix-list LOCAL-PREFIXES seq 20 permit 10.14.0.0/24
!
route-map ALLOW-ALL permit 10
!
route-map LOCAL-ONLY permit 10
 match ip address prefix-list LOCAL-PREFIXES
!
line vty
!
